name: Customize Repository

on:
  workflow_dispatch:
    inputs:
      myInput1:
        description: 'Input 1'
        required: true

jobs:
  customize:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Add your customization steps here
      - run: |
          # Replace placeholders, update files, etc.
          sed -i 's/PROJECT_NAME/${{ github.event.inputs.myInput1 }}/g' README.md
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions